name: CS-Simulator-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    # Add googletest subdirectory
    - name: Clone googletest repo
      run: git submodule update --init --recursive
        
    # Run tests on character class
    - name: Run the test file for character
      run: |
        cmake .
        make 
        cd bin
        ./characterTests
        
    #Run tests on validator class
    - name: Run the test file for character and course validator
      run: |
        cmake .
        make
        cd bin
        ./testCharacterValidator
